### ISSUE TITLE
Migrate token-farm to new Repository

### ISSUE THREAD

**Issue by Fuasmattn** [MaibornWolff/tlm-components#3]
AC

- [x] decide whether to use monorepo together with stencil repo or separate
- [x] existing pipelines from mwui / token-farm is working as before
- [x] developer docs are updated
- [x] figma token plugin integration is working and documented
- [x] pipeline (token transformation) is tested manually

**Comment by m-m-mic** [comment]
- we'll use monorepo for now
- migrating the script with javascript as output
- proper documentation with graphs (maybe in markdown?)
- Documentation of how to setup connection with Figma and how to push to repository (git commit conventions)
